CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_LAYER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

#stop the build from crashing on minor warnings
CONFIG_KCONFIG_WERROR=n

#CapsLock/NumLock lights 
CONFIG_ZMK_HID_INDICATORS=y
